# render.yaml
# Version 3, plus explicite et robuste pour le déploiement sur Render

services:
  # 1. Le service de la base de données PostgreSQL
  - type: psql         # Type officiel pour PostgreSQL
    name: jamboree-db  # Nom du service de base de données
    plan: free         # Plan gratuit (attention: effacé après 90j d'inactivité)
    
  # 2. Le service web pour l'application Django
  - type: web
    name: jamboree-app
    plan: free         # Important: spécifier le plan gratuit
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: "gunicorn jamboree_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true # Render génère une clé secrète
      - key: DATABASE_URL
        fromDatabase:
          name: jamboree-db # Doit correspondre au nom du service psql ci-dessus
          property: connectionString