# render.yaml
# Version corrigée pour le déploiement sur Render

services:
  # Un service web pour exécuter l'application Django
  - type: web
    name: jamboree-app # Le nom de votre application
    env: python
    plan: free # Spécifier le plan gratuit pour le service web également
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: "gunicorn jamboree_project.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jamboree-db # Doit correspondre au nom du service de BDD ci-dessous
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render génère une clé secrète sécurisée pour vous
      - key: PYTHON_VERSION
        value: 3.11.4 # Assurez-vous que cette version est supportée
      - key: DEBUG
        value: False

  # Une base de données PostgreSQL
  - type: db # <--- CORRECTION ICI. C'est "db" et non "psql"
    name: jamboree-db
    databaseName: jamboree_db # Nom interne de la base de données
    plan: free # Le plan gratuit de Render
    # Les données du plan gratuit sont effacées après 90 jours d'inactivité.
    # Pour un projet réel, passez à un plan payant (ex: 'starter').